# Renovate configuration validator
#
# This workflow validates changes proposed into Renovate configuration file,
# located .github/renovate.json5.
#
# Key Features:
# - Validate changes and prevent non-valid configuration to be used by Renovate.
#
# Process Stages:
# Configuration validation:
#    - Runs on PR into .github/renovate.json5 and validate changes.
#
# Required Secrets:
# - None
#
# Example Usage:
# Automatically triggered on:
# - Pull requests to .github/renovate.json5.
#
# Note: None.

name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/renovate-config-validator.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout configuration
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:43.160.2@sha256:e977df2dbd4b978cc301a0b4d8e0162ec4ce08bd205422c02c4cf55f52b67336
          docker run --rm --entrypoint "renovate-config-validator" \
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
          ${RENOVATE_IMAGE} "/renovate.json5"
